# Generated by Django 2.1.2 on 2019-01-01 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_article_read_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='read_num',
        ),
        migrations.RemoveField(
            model_name='article',
            name='readed_num',
        ),
    ]
